### ISSUE TITLE
BERT Classification files 

### ISSUE THREAD

**Issue by anna-pol** [deepmipt/Slavic-BERT-NER#1]
Sorry for bothering I was wondering could I do classification the pdf files to different folders by the context of the file. For example, I have 3 folders invoices, cv, and input folder and could I train with bert nlp folders cv and invoices so when smb will put the pdf file to the input folder it will automatically decide what it is cv or invoice.

**Comment by vikmary** [comment]
The discussion of the issue is conducted [here](https://github.com/deepmipt/DeepPavlov/issues/1003).
